#!/bin/bash
arg=$1
if [[ $arg == "312" ]]; then
	cp ~/.gitconfig.mshaibek ~/.gitconfig
	cp ~/.ssh/id_rsa.mshaibek ~/.ssh/id_rsa
	cp ~/.ssh/id_rsa.pub.mshaibek ~/.ssh/id_rsa.pub
elif [[ $arg == "tron" ]]; then
	cp ~/.gitconfig.tron ~/.gitconfig
	cp ~/.ssh/id_rsa.tron ~/.ssh/id_rsa
	cp ~/.ssh/id_rsa.pub.tron ~/.ssh/id_rsa.pub
else
	echo "Error: invalid argument"
	echo
	echo -ne "Example:\n 	chgit tron\n"
fi
